Repository danielsespitia/proyecto-top, pull requests merged in 2020-12, with the labels that each got.

#68 Fix013
  src/components/SanitaryRegister/SanitaryRegisterForm.js
  src/pages/SanitaryRegister.js
  src/store/actions/SanitaryRegister.actions.js
  src/store/reducers/SanitaryRegister.reducers.js
Labels: bug

#69 Rsv005 Create reservation
  src/components/Reservation/ReservationConfirmPayment.js
  src/pages/ReservationForm.js
  src/store/reservationReducer.js
Labels: enhancement

#70 Refactor actions creator
  src/components/Reservation/ReservationConfirmPayment.js
  src/components/Restaurant.js
  src/pages/ReservationForm.js
  src/pages/RestaurantProfile.js
  src/pages/Restaurants.js
  src/store/actions/Reservation.actions.js
  src/store/actions/Restaurant.actions.js
  src/store/index.js
  src/store/reducers/Reservation.reducer.js
  src/store/reducers/Restaurant.reducer.js
Labels: enhancement

#71 take out the link to a modal for sanitary register
  src/pages/ReservationForm.js
Labels: bug

#72 storage the pathuser for profile
  src/pages/SignIn.js
  src/pages/SignUp.js
  src/store/AuthContext.js
Labels: bug

#73 Feature rsv004
  src/components/Modal.js
  src/components/Modals/Modal.js
  src/components/Modals/ModalCompanion.js
  src/components/Modals/ModalStyles.js
  src/components/SanitaryRegister/SanitaryRegisterForm.js
  src/components/SanitaryRegister/SanitaryRegisterStyles.js
  src/pages/ReservationForm.js
  src/pages/SanitaryRegister.js
  src/pages/SanitaryRegisterCompanion.js
  src/store/AuthContext.js
Labels: enhancement

#74 Change Restaurant component names to getting match with files
  src/App.js
  src/components/RestaurantProfileForm.js
  src/components/RestaurantProfileViewForm.js
  src/pages/RestaurantProfile.js
  src/pages/RestaurantProfileView.js
  src/pages/SignIn.js
  src/pages/SignUp.js
Labels: enhancement

#75 Feature rsv004
  src/components/SanitaryRegister/SanitaryRegisterForm.js
  src/components/SanitaryRegister/SanitaryRegisterStyles.js
  src/pages/SanitaryRegisterCompanion.js
  src/store/actions/SanitaryRegisterCompanion.actions.js
  src/store/index.js
  src/store/reducers/SanitaryRegisterCompanion.reducer.js
Labels: enhancement

#76 Fix015
  src/components/Reservation/ReservationConfirmPayment.js
  src/components/Reservation/ReservationStyles.js
  src/pages/ReservationForm.js
Labels: documentation

#78 Fix prv001
  src/App.js
Labels: bug

#77 Feature hdr005
  src/App.js
  src/components/Header.js
  src/components/Header/Header.js
  src/components/Header/HeaderStyles.js
  src/components/Modals/ModalProfile.js
  src/components/Modals/ModalStyles.js
Labels: enhancement

#79 Move create reservation to the reservation form
  src/components/Reservation/ReservationConfirmPayment.js
  src/components/Restaurant.js
  src/pages/ReservationForm.js
  src/store/actions/Reservation.actions.js
  src/store/reducers/Reservation.reducer.js
Labels: enhancement

#81 Fix reservation form
  src/pages/ReservationForm.js
Labels: bug

#82 Fix017
  src/components/Reservation/ReservationConfirmPayment.js
  src/store/actions/Reservation.actions.js
  src/store/actions/SanitaryRegisterCompanion.actions.js
Labels: bug
